name=JoystickProtocol
version=1.0.0
author=Sakuhano
maintainer=Sakuhano <your.email@example.com>
sentence= Joystick input to button for usage in menus
paragraph=Used to navigate menus, uses ezButton for button input
url=https://github.com/Sakuhano/JoystickProtocol
architectures=ESP32, MEGA2560